services:
    #Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface:
        #alias: 'lexik_jwt_authentication.jwt_manager'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'